<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>div_clearfix</name>
   <tag></tag>
   <elementGuidId>d2d62ffe-1f52-4b29-a309-b027246312b1</elementGuidId>
   <selectorCollection>
      <entry>
         <key>BASIC</key>
         <value>id(&quot;tab1default&quot;)/div[@class=&quot;top-aqe-link&quot;]/div[@class=&quot;clearfix&quot;]</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//a[@id='attendance-logger-widget']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>div</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>clearfix</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;tab1default&quot;)/div[@class=&quot;top-aqe-link&quot;]/div[@class=&quot;clearfix&quot;]</value>
   </webElementProperties>
</WebElementEntity>
